# Generated by Django 5.2.8 on 2025-11-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('description', models.TextField(verbose_name='Descripción breve')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Año de publicación')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Externo (Google/OpenLib)')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='URL de Portada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-created_at'],
            },
        ),
    ]
